server:
  port: 8090
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis-Plus 配置（修正格式）
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'NULL'
  global-config:
    db-config:
      id-type: AUTO